### ISSUE TITLE
Can not start yoke after shutdown

### ISSUE THREAD

**Issue by hypersleep** [nanopack/yoke#10]
On the second and next runs yoke raises this error message:
```
bash-4.2$ yoke /etc/yoke/yoke.ini
Unable to create database, 'status' already exists. Please specify a different location.
```

That's because we're call `scribble.New` on every program run. And `scribble.New` can't load already existing database.

It looks like bug in https://github.com/nanobox-io/golang-scribble ?

**Comment by sdomino** [comment]
@hypersleep thank you for finding this. Scribble has since been updated and should now accommodate using an existing database (https://github.com/nanobox-io/golang-scribble/pull/8)
