### ISSUE TITLE
take a look at my failover software

### ISSUE THREAD

**Issue by nackstein** [nanopack/yoke#3]
hi,
I wrote a simple failover cluster manager in posix shell. I saw your project and I wonder if anyone of your team can be interested in contributing to mine, maybe just with some feedback.
that would be really appreciated.
my project is https://github.com/nackstein/back-to-work

thank you in advance
Luigi

**Comment by tylerflint** [comment]
hi @nackstein. I'll see if I can take some time to check it out in the next few days. Thanks for your interest. I'll go ahead and close this issue.

Thanks!
